baseurl: "/"
url: "https://t-dev-studio.github.io"

#ga_tracking: "G-EWM6PTTH99"

permalink: /:slug
markdown: kramdown

keep_files: [assets]
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .vscode/

collections:
  projects:
    output: true
    sort_by: "hierarchy"
    permalink: projects/:slug

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
